name: ⚙️ Build

on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: libs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.0
      - uses: taiga-family/ci/actions/setup/node@1.20.0
      - run: npm run build

concurrency:
  group: build-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
