name: ⚙️ Build

on:
    pull_request:
    push:
        branches: [main]

jobs:
    build:
        name: libs
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4.1.0
            - uses: taiga-family/ci/actions/setup/node@v1.23.0
            - run: npm run build
            - run: npm run lint
            - run: npm run prettier -- --check
            - run: npm run test
              env:
                  NODE_OPTIONS: --openssl-legacy-provider

concurrency:
    group: build-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
