name: ⚙️ CI

on:
    pull_request:
    push:
        branches: [main]

jobs:
    ci:
        runs-on: ubuntu-latest
        steps:
            - uses: taiga-family/ci/actions/setup/checkout@v1.35.0
            - uses: taiga-family/ci/actions/setup/node@v1.35.0
            - run: npm run check
            - run: npm run prettier -- --check
            - run: npm run build
              env:
                  NODE_OPTIONS: --openssl-legacy-provider
            - run: npm run test
              env:
                  NODE_OPTIONS: --openssl-legacy-provider

concurrency:
    group: ci-${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
